// Install Next PWA!!!
// https://dev.to/anuraggharat/pwa-with-nextjs-5178

import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Newsletter from "@/components/Newsletter/Newsletter";
import CallToOrder from "@/components/CallToOrder/CallToOrder";

//👇 Configure  local font object
const SegoeUI = localFont({ src: "../fonts/Segoe UI.ttf" });

export const metadata = {
  // title:    "Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport",
  title: {
    template: "  Jumia Nigeria Clone | %s",
    default: "Jumia Nigeria | Online Shopping — Clone",
  },
  description:
    "Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! ",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${SegoeUI.className} scroll-smooth`}>
        <Header />
        <Navbar />
        <CallToOrder />
        {children}
        <Newsletter />
        <Footer />
      </body>
    </html>
  );
}
