import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

//👇 Configure  local font object
const SegoeUI = localFont({ src: "../fonts/Segoe UI.ttf" });

export const metadata = {
  // title:    "Jumia Nigeria | Online Shopping for Electronics, Fashion, Home, Beauty &amp; Sport",
  title: {
    template: "  Jumia Nigeria Clone | %s",
    default: "Jumia Nigeria | Online Shopping — Clone",
  },
  description:
    "Jumia Nigeria the #1 of Online Shopping in Nigeria - Shop Online All Products : Smartphones, Appliances, Clothing... ✓ Top Brands :  Samsung, Xiaomi, Adidas... ✓ Best prices in Nigeria ✓ Order now and enjoy pay on delivery ! ",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${SegoeUI.className} scroll-smooth`}>{children}</body>
    </html>
  );
}
